# input is a python file which contains a class or a saved model. Currently, only sklearn model is supported
input_model:
  model_script: False
  saved_model:
    sklearn: True

# "classification" or "regression"
task:
  classification:
    enabled: True
    type:
      binary: False
  regression:
    enabled: False
# choose shap explainer
explainer:
  enabled: True
  type:
    #Advantage: model agnostic; Disadvantage: computational cost
    KernelExplainer: True
    #Advantage: efficient with high dimensional data
    PartitionExplainer: False
    #Advantage: optimized for linear model, efficient; Disadvantage: model specific
    LinearExplainer: False
    #Advantage: optimized for tree model, efficient; Disadvantage: model specific
    TreeExplainer: False

# enable bootstrapping
bootstrapping:
  enabled: True
  parameters:
    bootstrap_sample_percentage: 0.9
    bootstrap_iteration_number: 20  # the number of random sampling with replacement will be performed, a larger number will lead to more time for computation but more robust estimates
    bootstrapping_metrics:
      regression:
        mae: True      #Mean Absolute Error
        mse: True      #Mean Squared Error
        rmse: True     #Root Mean Squared Error
      classification:
        mcc: True      #Matthews Correlation Coefficient
        bas: True      #balanced accuracy score
        ras: True      #roc auc score


# enable LIME interpreter
LIME:
  enabled: True
  parameters:
    LIME_datapoint_index: 10 # the index of instance for LIME interpretation
    LIME_feature_number: 10 # the number of features to be used in the explanation.
    LIME_sample_number: 20 # refers to the number of perturbed samples to generate

